export const SIGNIN = "SIGNIN";
export const SIGNINLOADING = "SIGNINLOADING";
export const SIGNINSUCCESS = "SIGNINSUCCESS";
export const SIGNINERROR = "SIGNINERROR";
export const CLEARSIGNINSTATE = "CLEARSIGNINSTATE";

//SIGN-UP
export const SIGNUP = "SIGNUP";
export const SIGNUPLOADING = "SIGNUPLOADING";
export const SIGNUPSUCCESS = "SIGNUPSUCCESS";
export const SIGNUPERROR = "SIGNUPERROR";
export const CLEARSIGNUPSTATE = "CLEARSIGNUPSTATE";
