//SIGN-In actions
export const SIGNIN = "SIGNIN";
export const SIGNINLOADING = "SIGNINLOADING";
export const SIGNINSUCCESS = "SIGNINSUCCESS";
export const SIGNINERROR = "SIGNINERROR";
export const CLEARSIGNINSTATE = "CLEARSIGNINSTATE";

//SIGN-Up actions
export const SIGNUP = "SIGNUP";
export const SIGNUPLOADING = "SIGNUPLOADING";
export const SIGNUPSUCCESS = "SIGNUPSUCCESS";
export const SIGNUPERROR = "SIGNUPERROR";
export const CLEARSIGNUPSTATE = "CLEARSIGNUPSTATE";

//Products actions
export const FETCH_PRODUCTS_REQUEST = "FETCH_PRODUCTS_REQUEST";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAILURE = "FETCH_PRODUCTS_FAILURE";
